channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit
  - pybigwig=0.3.17
  - prettytable
  - pynvml
  - pip:
    - pysam==0.15.1
    - pybedtools
    - janggu[tf2]>=0.10.0
    - ray[tune]==1.1.0
    - aioredis==1.3.1      
    - dirichletcal
    - jax
    - jaxlib
    - autograd
