channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip=22.0.4
  - numpy=1.21.2
  - cudatoolkit=11.3
  - pytorch=1.10.2
  - torchvision=0.11.3
  - torchaudio=0.10.2
  - pybigwig=0.3.17
  - prettytable=3.2.0
  - pynvml=11.4.1
  - bedtools=2.30.0
  - pip:
    - scikit-learn==0.24.2
    - pysam==0.15.1
    - pybedtools==0.9.0
    - janggu[tf2]>=0.10.0
    - ray[tune]==1.0.0 #updated
    - aioredis==1.3.1      
    - aiohttp==3.7.4
    - dirichletcal
    - jax==0.3.1
    - jaxlib==0.3.0
    - autograd==1.3
