channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip=22.0.4
  - numpy=1.21.2
  - cudatoolkit=11.3
  - pytorch=1.10.2
  - pybigwig=0.3.17
  - prettytable=3.2.0
  - pynvml=11.4.1
  - bedtools=2.30.0
  - pip:
    - h5py==2.10.0
    - scipy==1.4.1
    - scikit-learn==0.24.2
    - biopython==1.77
    - pysam==0.15.1
    - pybedtools==0.9.0
    - ray[tune]==1.0.0 #updated
    - dirichletcal
    - jax==0.3.1
    - jaxlib==0.3.0
    - autograd==1.3
